version: "3.9"

services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"

  dealerapi:
    image: node:16
    container_name: dealerapi
    working_dir: /app
    volumes:
      - ./server/database:/app
    command: bash -c "npm install && node server.js"
    ports:
      - "3030:3030"
    depends_on:
      - mongo
